server:
  port: 80

spring:
  application:
    name: cloud-order-consul-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #linux 安装的consul需要配置hostname，否则说不健康
        # hostname: localhost
        service-name: ${spring.application.name}