server:
  port: 3344

spring:
  application:
    name: cloud-config-center  #注册进eureka的微服务名
  cloud:
    config:
      server:
        git:
          # uri: git@github.com:huangjia7/springcloud_config.git
          # uri: https://github.com/huangjia7/springcloud_config.git
          uri: https://gitee.com/raul2016/spring-config.git
          search-paths:
            - springcloud_config
          force-pull: true
          username: zouyi202@163.com
          password: raulgoal7
      label: master
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    #register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://locahost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka